services:
  web:
    build: .
    command: gunicorn app.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./media:/app/media
       - static:/app/static
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: beermat
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: sqeu2-sqeu2
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "8000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static:/app/static
      - media:/app/media
    depends_on:
      - web

volumes:
  postgres_data:
  static:
  media:
