# Generated by Django 5.2.5 on 2025-08-12 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beermat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('maker', models.CharField(max_length=50, verbose_name='Maker')),
                ('country', models.CharField(max_length=50, verbose_name='Country')),
                ('weight', models.FloatField(verbose_name='Weight')),
                ('diameter', models.FloatField(verbose_name='Diameter')),
                ('thickness', models.FloatField(verbose_name='Thickness')),
                ('when', models.DateTimeField(verbose_name='When')),
                ('where', models.CharField(max_length=50, verbose_name='where')),
                ('description', models.TextField(max_length=500, verbose_name='Description')),
            ],
        ),
    ]
