# Generated by Django 5.2.5 on 2025-08-12 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_beermat_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='beermat',
            name='name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Maker'),
        ),
        migrations.AlterField(
            model_name='beermat',
            name='country',
            field=models.CharField(blank=True, max_length=50, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='beermat',
            name='description',
            field=models.TextField(blank=True, max_length=500, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='beermat',
            name='diameter',
            field=models.FloatField(null=True, verbose_name='Diameter (mm)'),
        ),
        migrations.AlterField(
            model_name='beermat',
            name='maker',
            field=models.CharField(blank=True, max_length=50, verbose_name='Maker'),
        ),
        migrations.AlterField(
            model_name='beermat',
            name='thickness',
            field=models.FloatField(null=True, verbose_name='Thickness (mm)'),
        ),
        migrations.AlterField(
            model_name='beermat',
            name='weight',
            field=models.FloatField(blank=True, null=True, verbose_name='Weight (g)'),
        ),
        migrations.AlterField(
            model_name='beermat',
            name='when',
            field=models.DateTimeField(null=True, verbose_name='When'),
        ),
        migrations.AlterField(
            model_name='beermat',
            name='where',
            field=models.CharField(blank=True, max_length=50, verbose_name='where'),
        ),
    ]
