# Generated by Django 5.2.5 on 2025-08-14 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_beermat_name_alter_beermat_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='beermat',
            name='photo_mat',
            field=models.ImageField(blank=True, default='photo_of_mat.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='beermat',
            name='name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Name'),
        ),
    ]
