# Generated by Django 5.2.5 on 2025-08-23 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_beermat_photo_mat_alter_beermat_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeermatForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_mat', models.ImageField(blank=True, default='beermats/default.png', null=True, upload_to='beermats/')),
                ('maker', models.CharField(blank=True, max_length=50, verbose_name='Maker')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='Name')),
                ('country', models.CharField(blank=True, max_length=50, verbose_name='Country')),
                ('weight', models.FloatField(blank=True, null=True, verbose_name='Weight (g)')),
                ('diameter', models.FloatField(null=True, verbose_name='Diameter (mm)')),
                ('thickness', models.FloatField(null=True, verbose_name='Thickness (mm)')),
            ],
        ),
        migrations.DeleteModel(
            name='Beermat',
        ),
    ]
