# Generated by Django 5.2.5 on 2025-08-23 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_beermatform_delete_beermat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beermatform',
            name='diameter',
            field=models.FloatField(blank=True, null=True, verbose_name='Diameter (mm)'),
        ),
        migrations.AlterField(
            model_name='beermatform',
            name='thickness',
            field=models.FloatField(blank=True, null=True, verbose_name='Thickness (mm)'),
        ),
    ]
