# Generated by Django 5.2.5 on 2026-03-15 15:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Beermat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('brewery', models.CharField(blank=True, max_length=120)),
                ('style', models.CharField(blank=True, max_length=120)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CollectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(blank=True, max_length=255)),
                ('acquired_at', models.DateTimeField(auto_now_add=True)),
                ('beermat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collected_by', to='beermats.beermat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-acquired_at'],
                'unique_together': {('user', 'beermat')},
            },
        ),
    ]
