# Generated by Django 5.2.5 on 2026-03-15 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beermats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='beermat',
            name='approved',
            field=models.BooleanField(default=False, help_text='Approve to show in public catalog'),
        ),
        migrations.AddField(
            model_name='beermat',
            name='beer_name',
            field=models.CharField(blank=True, help_text='Beer name / brand', max_length=120),
        ),
        migrations.AddField(
            model_name='beermat',
            name='diameter_mm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='beermat',
            name='photo_back',
            field=models.ImageField(blank=True, null=True, upload_to='beermats/'),
        ),
        migrations.AddField(
            model_name='beermat',
            name='photo_front',
            field=models.ImageField(blank=True, null=True, upload_to='beermats/'),
        ),
        migrations.AddField(
            model_name='beermat',
            name='thickness_mm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='beermat',
            name='weight_g',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='beermat',
            name='name',
            field=models.CharField(help_text='Coaster name', max_length=120),
        ),
    ]
