# Generated by Django 5.2.5 on 2026-03-15 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beermats', '0003_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='beermat',
            name='country',
            field=models.CharField(blank=True, help_text='Country of origin', max_length=80),
        ),
    ]
