# Generated by Django 5.2.5 on 2026-03-15 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beermats', '0004_beermat_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='beermat',
            name='approved_at',
            field=models.DateTimeField(blank=True, help_text='When the beermat was approved', null=True),
        ),
    ]
