# Generated by Django 5.2.5 on 2026-03-15 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beermats', '0005_beermat_approved_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='beermat',
            name='photo_back_thumb',
            field=models.ImageField(blank=True, null=True, upload_to='beermats/thumbs/'),
        ),
        migrations.AddField(
            model_name='beermat',
            name='photo_front_thumb',
            field=models.ImageField(blank=True, null=True, upload_to='beermats/thumbs/'),
        ),
        migrations.AlterField(
            model_name='beermat',
            name='photo_back',
            field=models.ImageField(blank=True, null=True, upload_to='beermats/originals/'),
        ),
        migrations.AlterField(
            model_name='beermat',
            name='photo_front',
            field=models.ImageField(blank=True, null=True, upload_to='beermats/originals/'),
        ),
    ]
