# Generated by Django 5.2.12 on 2026-03-24 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beermats', '0007_newsitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsitem',
            name='body',
            field=models.TextField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='published',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
